name: Laravel

on:
  push:
    branches: [ master ]
 

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run:  |
        composer self update
        composer install -q --no-interaction -- --prefer-source -- --dev
        cp .env.example .env
    - name: Generate key
      run: php artisan key:generate
    - name: JWT secret
      run: php artisan jwt:secret
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
   
    
